credentials:
  usernames:
    peeet01:
      email: peeet01@gmail.com
      name: peeet01
      password: '$2b$12$KIXiOJnFMRHxVWZNUXy8guB2aA4RbDcGm9ik9x8XVkGBiRzjG9NNe'  # Teszt123

    admin:
      email: admin@reflectai.hu
      name: Admin Felhaszn치l칩
      password: '$2b$12$7ZPaF1YXUkOWbClyxyRU4ub16H8HZs1NCEfw8dyUO9z5HTGv01oQO'  # Admin123

    kutato1:
      email: kutato1@reflectai.hu
      name: Kutat칩 Felhaszn치l칩
      password: '$2b$12$xNmCfzEYm4.qgrWqDdByEux3WkOiHV/dk9xAWhuRYvlQW8A.9gPZa'  # Kutato2024

cookie:
  name: reflectai_auth
  key: some_signature_key  # 游댐 FONTOS: Ez okozta a hib치t, most benne van!
  expiry_days: 30

preauthorized:
  emails:
    - peeet01@gmail.com
    - admin@reflectai.hu
    - kutato1@reflectai.hu
